# Generated by Django 4.2.5 on 2023-10-02 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('organization_logo', models.ImageField(upload_to='images/company-logo/')),
                ('tc', models.BooleanField()),
                ('is_company', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=50)),
                ('company_phone_number', models.IntegerField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
