# Generated by Django 4.2.5 on 2023-10-02 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_company',
        ),
    ]
