# Generated by Django 4.2.3 on 2023-09-30 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('permission', models.CharField(choices=[('Admin', 'Admin'), ('Contributor', 'Contributor'), ('Consumer', 'Consumer')], max_length=50)),
                ('is_addUser', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
