# Generated by Django 4.2.5 on 2023-10-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0002_alter_adduser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
