# Generated by Django 4.2.5 on 2023-10-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0003_alter_adduser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adduser',
            old_name='user',
            new_name='organization',
        ),
    ]
