# Generated by Django 4.2.5 on 2023-09-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
