# Generated by Django 4.2.5 on 2023-09-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_pics/profile.jpg', upload_to='images/account/'),
        ),
    ]
